version: '3'

services:

  WPPC-SERVER:
    build:
      context: ./wppconnect-server
      dockerfile: Dockerfile
    restart: always
    image: wppconnect-server
    container_name: WPPC-SERVER
    hostname: WPPC-SERVER
    entrypoint: docker-entrypoint.sh yarn dev
    networks:
      - WPPC-NETWORK
    volumes:
      - ./sessions:/home/node/app/tokens/        
    tty: true

  WPPC-FRONT:
    build:
      context: ./wppconnect-front
      dockerfile: Dockerfile
    image: wppconnect-front
    container_name: WPPC-FRONT
    hostname: WPPC-FRONT
    entrypoint: docker-entrypoint.sh npm run serve -- --port 3000
    networks:
      - WPPC-NETWORK
    tty: true
    depends_on:
      - WPPC-SERVER

  WPPC-PROXY:
    build:
      context: ./wppconnect-nginx
      dockerfile: Dockerfile
    container_name: WPPC-PROXY
    hostname: WPPC-PROXY
    entrypoint: nginx -g "daemon off;"
    ports:
      - "2080:8080"
      - "8081:8081"
    networks:
      - WPPC-NETWORK
    depends_on:
      - WPPC-FRONT

networks:
  WPPC-NETWORK:
    name: WPPC-NETWORK
    driver: bridge