version: '3'

services: 

  wppc-server:
    build: 
      context: ./wppconnect-server
      dockerfile: Dockerfile
    restart: always
    image: wppconnect-server
    container_name: WPPC-SERVER
    hostname: WPPC-SERVER
    entrypoint: docker-entrypoint.sh yarn dev
    networks: 
      - wppc-network
    tty: true
  
  wppc-front:
    build: 
      context: ./wppconnect-front
      dockerfile: Dockerfile
    image: wppconnect-front
    container_name: WPPC-FRONT
    hostname: WPPC-FRONT
    entrypoint: docker-entrypoint.sh yarn start
    networks: 
      - wppc-network
    tty: true
    depends_on:
      - wppconnect-server

  wppc-nginx:
    build: 
      context: ./wppconnect-nginx
      dockerfile: Dockerfile
    container_name: WPPC-NGINX
    hostname: WPPC-NGINX
    entrypoint: nginx -g "daemon off;"
    ports:
      - "8080:8080"
      - "8081:8081"
    networks: 
      - wppc-network
    depends_on:
      - wppconnect-front

networks: 
  wppc-network:
    name: wppc-network
    driver: bridge 