version: '3'

services: 

  wppconnect-server:
    build:
      context: ./wppconnect-server
      dockerfile: Dockerfile
    restart: always
    image: wppconnect-server
    container_name: wppconnect-server
    hostname: wppconnect-server
    entrypoint: docker-entrypoint.sh yarn dev
    networks:
      - wpp-network
    tty: true
    volumes:
      - ./sessions:/home/node/app/tokens/

  wppconnect-nginx:
    build:
      context: ./wppconnect-nginx
      dockerfile: Dockerfile
    restart: always
    container_name: wppconnect-nginx
    entrypoint: nginx -g "daemon off;"
    ports:
      - "21465:21465"
    networks:
      - wpp-network
    depends_on:
      - wppconnect-server

networks: 
  wpp-network:
    name: wpp-network
    driver: bridge 