version: '3'

services: 

  wppconnect-server:
    build: 
      context: ./
      dockerfile: SERVER.Dockerfile
    restart: always
    image: wppconnect-server
    container_name: wppconnect-server
    hostname: wppconnect-server
    entrypoint: docker-entrypoint.sh yarn dev
    networks: 
      - WPPCONNECT-NETWORK
    volumes:
      - WPPCONNECT-SESSION:/home/node/app/tokens
    tty: true
  
  wppconnect-front:
    build: 
      context: ./
      dockerfile: FRONT.Dockerfile
    image: wppconnect-front
    container_name: wppconnect-front
    hostname: wppconnect-front
    entrypoint: docker-entrypoint.sh yarn start
    networks: 
      - WPPCONNECT-NETWORK
    tty: true
    depends_on:
      - wppconnect-server

  wppconnect-nginx:
    build: 
      context: ./
      dockerfile: NGINX.Dockerfile
    container_name: wppconnect-nginx
    entrypoint: nginx -g "daemon off;"
    ports:
      - "8080:8080"
      - "8081:8081"
    networks: 
      - WPPCONNECT-NETWORK
    depends_on:
      - wppconnect-front

volumes:
  WPPCONNECT-SESSION:

networks: 
  WPPCONNECT-NETWORK:
    name: WPPCONNECT-NETWORK
    driver: bridge 