version: '3'

services: 

  WPPC-SERVER-1:
    build: 
      context: ./wppconnect-server
      dockerfile: Dockerfile
    restart: always
    image: wppconnect-server
    container_name: WPPC-SERVER-1
    hostname: WPPC-SERVER-1
    entrypoint: docker-entrypoint.sh yarn dev
    networks: 
      WPPC-NETWORK:
        ipv4_address: 172.20.0.2
    tty: true
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
    depends_on:
      - WPPC-REDIS
    
  WPPC-SERVER-2:
    build: 
      context: ./wppconnect-server
      dockerfile: Dockerfile
    restart: always
    image: wppconnect-server
    container_name: WPPC-SERVER-2
    hostname: WPPC-SERVER-2
    entrypoint: docker-entrypoint.sh yarn dev
    networks: 
      WPPC-NETWORK:
        ipv4_address: 172.20.0.3
    tty: true
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
    depends_on:
      - WPPC-SERVER-1
      - WPPC-REDIS

  WPPC-REDIS:
    restart: always
    image: redis
    container_name: WPPC-REDIS
    hostname: WPPC-REDIS
    ports:
      - "6379:6379"
    networks: 
      WPPC-NETWORK:
        ipv4_address: 172.20.0.7
    volumes:
      - ./redis-data:/data
  
  WPPC-NGINX:
    build: 
      context: ./wppconnect-nginx
      dockerfile: Dockerfile
    container_name: WPPC-NGINX
    hostname: WPPC-NGINX
    entrypoint: nginx -g "daemon off;"
    ports:
      - "8081:8081"
    networks: 
      WPPC-NETWORK:
        ipv4_address: 172.20.0.8
    volumes: 
      - ./wppconnect-nginx/conf.d:/etc/nginx/conf.d
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
    depends_on:
      - WPPC-SERVER-1
      - WPPC-SERVER-2
      - WPPC-REDIS

networks: 
  WPPC-NETWORK:
    name: WPPC-NETWORK
    driver: bridge 
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16